sudo: required

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

before_install:
  - docker --version
  - docker pull schickling/latex
  - docker pull tzrlk/rocker-compose
  - docker pull tzrlk/kscript

script: ./build.sh

deploy:

  - provider:     releases
    skip_cleanup: true
    file:         _build/main.pdf
    on:           { tags: true }
    api_key:      { secure: "gnsfglbExVKj93OOskhUzxwxXYa8Tkcw5X2ARW95+iJphY/E3htuV2dLeb4950woOssRol2aGrtS82iQ6EZ8NIt2Yzq+V4MEW+IHipOpBriiVdiR9I4ofxq8I30IUtE8eR/VkL/AC7TO9TIkmS2PB+6cECoDNVH4V8CeF0GKmYjtE2E2bnAP3XgykuHxZ3S2Kvs3Y6r1TPmORsxry2NgkMHQqvUARcb3uWqcP//zUlLRGIcqkomILKH6BuPuKVLwc5aTsVoZwutYIvlK2l53AkwIk92wYOjnkdHBwrLJ4RhHtur8TPU5F9TZaG6uXwaIUEcXcpKFCcYZUZGpg9i55HejzMkX8tVO93u1zLDnBWXi/Mrb2w7VezihdcN30ODLyi1nlp+dZms82GyLijRIMwhNfryoip0BGoFIqLCoILZMO3H0ywtrrVPkhe+jm0xkM1lPJwngl6GTM2ep1VTkx7txqEUSgsVr11WkAoHamhjwyh7At2f4bpme5mBG5QCWlSLA3g5IX0qOw2NgzneRw+YstqfCumPySHZLMZ9SdJZTI45xwRgfKJENiOQYISaUbqD0/w4wuKsnTOMb+2AOdd2Bldnri/03zHn66KP50iqitPfiDbN4S5fztSjEVz5l2occ4h3FpLQ3NAFClHcFLrWOhVC/Ci0kGnrfkztPp5M=" }

