language: java
jdk:      [ oraclejdk8 ]

dist: trusty
sudo: false

addons:
  apt:
    packages:
      - latex-xcolor
      - texlive
      - texlive-latex-extra
      - xzdec

before_install:
  - bash -c "curl -s \"https://get.sdkman.io\" | bash"
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"
  - tlmgr init-usertree
  - tlmgr option repository ftp://tug.org/historic/systems/texlive/2013/tlnet-final
  - tlmgr update --self

install:
  - sdk install maven
  - sdk install kotlin
  - sdk install kscript

after_install:
  - mvn --version
  - kotlin --version
  - kscript --version
  - pdflatex -version

script:
  - make compile
  - make texdeps
  - make render

deploy:

  - provider:     releases
    skip_cleanup: true
    file:         _build/main.pdf
    on:           { tags: true }
    api_key:      { secure: "gnsfglbExVKj93OOskhUzxwxXYa8Tkcw5X2ARW95+iJphY/E3htuV2dLeb4950woOssRol2aGrtS82iQ6EZ8NIt2Yzq+V4MEW+IHipOpBriiVdiR9I4ofxq8I30IUtE8eR/VkL/AC7TO9TIkmS2PB+6cECoDNVH4V8CeF0GKmYjtE2E2bnAP3XgykuHxZ3S2Kvs3Y6r1TPmORsxry2NgkMHQqvUARcb3uWqcP//zUlLRGIcqkomILKH6BuPuKVLwc5aTsVoZwutYIvlK2l53AkwIk92wYOjnkdHBwrLJ4RhHtur8TPU5F9TZaG6uXwaIUEcXcpKFCcYZUZGpg9i55HejzMkX8tVO93u1zLDnBWXi/Mrb2w7VezihdcN30ODLyi1nlp+dZms82GyLijRIMwhNfryoip0BGoFIqLCoILZMO3H0ywtrrVPkhe+jm0xkM1lPJwngl6GTM2ep1VTkx7txqEUSgsVr11WkAoHamhjwyh7At2f4bpme5mBG5QCWlSLA3g5IX0qOw2NgzneRw+YstqfCumPySHZLMZ9SdJZTI45xwRgfKJENiOQYISaUbqD0/w4wuKsnTOMb+2AOdd2Bldnri/03zHn66KP50iqitPfiDbN4S5fztSjEVz5l2occ4h3FpLQ3NAFClHcFLrWOhVC/Ci0kGnrfkztPp5M=" }

